#!/bin/bash
set -e

flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
flatpak install flathub io.missioncenter.MissionCenter -y
flatpak install flathub com.github.GradienceTeam.Gradience -y


dconf update 
glib-compile-schemas /usr/share/glib-2.0/schemas