#!/bin/bash
set -e

glib-compile-schemas /usr/share/glib-2.0/schemas
update-desktop-database -q /usr/share/applications
gtk-update-icon-cache -f /usr/share/icons/hicolor

plymouth-set-default-theme -R otis-main
update-initramfs -u -k all