#!/bin/bash
set -e

glib-compile-schemas /usr/share/glib-2.0/schemas
gtk-update-icon-cache -f -t /usr/share/icons/otis
update-desktop-database -q /usr/share/applications
gtk-update-icon-cache -f /usr/share/icons/hicolor

update-alternatives --install /usr/share/plymouth/themes/otis-main.plymouth otis-main /usr/share/plymouth/themes/otis-main/otis-main.plymouth 200
update-alternatives --install /usr/share/plymouth/themes/text.plymouth text /usr/share/plymouth/themes/otis-text/otis-text.plymouth 200

update-alternatives --set otis-main /usr/share/plymouth/themes/otis-main/otis-main.plymouth
update-alternatives --set text /usr/share/plymouth/themes/otis-text/otis-text.plymouth

plymouth-set-default-theme -R otis-main
update-initramfs -u -k all